#define MODEL_Root              0x1C
#define MODEL_Bush6             0x1B
#define MODEL_Bush5             0x1A
#define MODEL_Bush4             0x19
#define MODEL_Bush3             0x18
#define MODEL_Bush2             0x17
#define MODEL_Bush1             0x16
#define MODEL_Tree2             0x15
#define MODEL_TreeLeaves2       0x14
#define MODEL_TreeTrunk2        0x13
#define MODEL_Tree1             0x12
#define MODEL_TreeLeaves1       0x11
#define MODEL_TreeTrunk1        0x10
#define MODEL_BigTree2          0xF
#define MODEL_BigTreeLeaves2    0xE
#define MODEL_BigTreeTrunk2     0xD
#define MODEL_BigTree1          0xC
#define MODEL_BigTreeLeaves1    0xB
#define MODEL_BigTreeTrunk1     0xA
#define MODEL_Sea               0x9
#define MODEL_OceanFloor        0x8
#define MODEL_WaterSurface      0x7
#define MODEL_Waves             0x6
#define MODEL_Island            0x5
#define MODEL_Dock              0x4
#define MODEL_FloorOuter2       0x3
#define MODEL_FloorOuter1       0x2
#define MODEL_FloorInner        0x1
#define MODEL_IslandWall        0x0

