#define COLLIDER_Root           0x18
#define COLLIDER_Foliage        0x17
#define COLLIDER_Bush8          0x16
#define COLLIDER_Bush7          0x15
#define COLLIDER_Bush6          0x14
#define COLLIDER_Bush5          0x13
#define COLLIDER_Bush4          0x12
#define COLLIDER_Bush3          0x11
#define COLLIDER_Bush2          0x10
#define COLLIDER_Bush1          0xF
#define COLLIDER_Tree3          0xE
#define COLLIDER_Tree2          0xD
#define COLLIDER_Tree1          0xC
#define COLLIDER_DrawnCollider  0xB
#define COLLIDER_MeshCollider   0xA
#define COLLIDER_MeshCollider   0x9
#define COLLIDER_MeshCollider   0x8
#define COLLIDER_MeshCollider   0x7
#define COLLIDER_MeshCollider   0x6
#define COLLIDER_MeshCollider   0x5
#define COLLIDER_MeshCollider   0x4
#define COLLIDER_MeshCollider   0x3
#define COLLIDER_Dock           0x2
#define COLLIDER_WallsIsland    0x1
#define COLLIDER_FloorIsland    0x0

#define ZONE_Root               0x4
#define ZONE_FloorIsland        0x3
#define ZONE_MeshCollider       0x2
#define ZONE_MeshCollider       0x1
#define ZONE_Dock               0x0

