#define MODEL_Root              0x41
#define MODEL_MeshModel         0x40
#define MODEL_Leaves            0x3F
#define MODEL_RockStep2         0x3E
#define MODEL_RockStep1         0x3D
#define MODEL_Bush8             0x3C
#define MODEL_Bush7             0x3B
#define MODEL_Bush6             0x3A
#define MODEL_Bush5             0x39
#define MODEL_Bush4             0x38
#define MODEL_Bush3             0x37
#define MODEL_Bush2             0x36
#define MODEL_o103              0x35
#define MODEL_o103              0x34
#define MODEL_o53               0x33
#define MODEL_o181              0x32
#define MODEL_o178              0x31
#define MODEL_o102              0x30
#define MODEL_o103              0x2F
#define MODEL_o211              0x2E
#define MODEL_o210              0x2D
#define MODEL_o209              0x2C
#define MODEL_o55               0x2B
#define MODEL_o54               0x2A
#define MODEL_o53               0x29
#define MODEL_RocksBack         0x28
#define MODEL_Split Model       0x27
#define MODEL_DrawnModel        0x26
#define MODEL_CylinderModel     0x25
#define MODEL_o119              0x24
#define MODEL_o118              0x23
#define MODEL_FlowerPatch       0x22
#define MODEL_o248              0x21
#define MODEL_BushBack2         0x20
#define MODEL_o169              0x1F
#define MODEL_o168              0x1E
#define MODEL_BushBack1         0x1D
#define MODEL_o119              0x1C
#define MODEL_o118              0x1B
#define MODEL_o35               0x1A
#define MODEL_o34               0x19
#define MODEL_o468              0x18
#define MODEL_o466              0x17
#define MODEL_hana8             0x16
#define MODEL_Split Model       0x15
#define MODEL_CylinderModel     0x14
#define MODEL_CandyCane         0x13
#define MODEL_Bush1             0x12
#define MODEL_Tree3             0x11
#define MODEL_TreeLeaves3       0x10
#define MODEL_TreeTrunk3        0xF
#define MODEL_Tree2             0xE
#define MODEL_TreeLeaves2       0xD
#define MODEL_TreeTrunk2        0xC
#define MODEL_Tree1             0xB
#define MODEL_TreeLeaves1       0xA
#define MODEL_TreeTrunk1        0x9
#define MODEL_Sea               0x8
#define MODEL_OceanFloor        0x7
#define MODEL_WaterSurface      0x6
#define MODEL_Waves             0x5
#define MODEL_Island            0x4
#define MODEL_Dock              0x3
#define MODEL_Floor             0x2
#define MODEL_IslandWall2       0x1
#define MODEL_IslandWall1       0x0

