#define MODEL_Root              0x1E
#define MODEL_Sea               0x1D
#define MODEL_OceanFloor        0x1C
#define MODEL_WaterSurface      0x1B
#define MODEL_Ship              0x1A
#define MODEL_Mast              0x19
#define MODEL_Windows           0x18
#define MODEL_Trim              0x17
#define MODEL_Hull              0x16
#define MODEL_CannonballCrate   0x15
#define MODEL_Cannonballs       0x14
#define MODEL_StairWall         0x13
#define MODEL_Staircases        0x12
#define MODEL_Railing           0x11
#define MODEL_CannonPosts       0x10
#define MODEL_Cannons           0xF
#define MODEL_Grate             0xE
#define MODEL_Ladder            0xD
#define MODEL_MoneyBags         0xC
#define MODEL_dai               0xB
#define MODEL_o287              0xA
#define MODEL_waku1             0x9
#define MODEL_yuka              0x8
#define MODEL_g49               0x7
#define MODEL_waku2             0x6
#define MODEL_waku              0x5
#define MODEL_yuka2             0x4
#define MODEL_g59               0x3
#define MODEL_g61               0x2
#define MODEL_g58               0x1
#define MODEL_g60               0x0

