#define MODEL_Root              0x26
#define MODEL_MoneyBags         0x25
#define MODEL_ChestStar         0x24
#define MODEL_ChestTrim         0x23
#define MODEL_Chest             0x22
#define MODEL_GoldPile          0x21
#define MODEL_CannonStands      0x20
#define MODEL_Cannon            0x1F
#define MODEL_TableCloth        0x1E
#define MODEL_Papers            0x1D
#define MODEL_Crates            0x1C
#define MODEL_CannonBallCrate   0x1B
#define MODEL_CannonballPile    0x1A
#define MODEL_WheelPole         0x19
#define MODEL_Wheel             0x18
#define MODEL_DoorTrim          0x17
#define MODEL_Door              0x16
#define MODEL_Trim              0x15
#define MODEL_Ladders           0x14
#define MODEL_LatchDoorBase     0x13
#define MODEL_LatchDoor         0x12
#define MODEL_Railing           0x11
#define MODEL_SailsBack         0x10
#define MODEL_SailLogo          0xF
#define MODEL_Sails             0xE
#define MODEL_Grate             0xD
#define MODEL_Staircases        0xC
#define MODEL_SailMast3         0xB
#define MODEL_SailMast2         0xA
#define MODEL_SailMast1         0x9
#define MODEL_CrowsNestRailing  0x8
#define MODEL_CrowsNestBase     0x7
#define MODEL_CrowsNest         0x6
#define MODEL_MastBase          0x5
#define MODEL_Mast              0x4
#define MODEL_Walls             0x3
#define MODEL_Deck              0x2
#define MODEL_Windows           0x1
#define MODEL_Hull              0x0

