#define MODEL_Root              0x17
#define MODEL_ship              0x16
#define MODEL_sail              0x15
#define MODEL_mast              0x14
#define MODEL_hull              0x13
#define MODEL_water             0x12
#define MODEL_g1                0x11
#define MODEL_exit              0x10
#define MODEL_g7                0xF
#define MODEL_b_w2              0xE
#define MODEL_b_w               0xD
#define MODEL_g11               0xC
#define MODEL_b_s2              0xB
#define MODEL_b_s               0xA
#define MODEL_g8                0x9
#define MODEL_b_e2              0x8
#define MODEL_b_e               0x7
#define MODEL_g12               0x6
#define MODEL_b_n2              0x5
#define MODEL_b_n               0x4
#define MODEL_g2                0x3
#define MODEL_g10               0x2
#define MODEL_g5                0x1
#define MODEL_o3                0x0

