#define MODEL_Root              0x52
#define MODEL_Leaves            0x51
#define MODEL_Flowers           0x50
#define MODEL_RocksBack         0x4F
#define MODEL_BushesBack        0x4E
#define MODEL_Fence             0x4D
#define MODEL_RockTable         0x4C
#define MODEL_Bush10            0x4B
#define MODEL_Bush9             0x4A
#define MODEL_Bush8             0x49
#define MODEL_Bush7             0x48
#define MODEL_Bush6             0x47
#define MODEL_Bush5             0x46
#define MODEL_Bush4             0x45
#define MODEL_Bush3             0x44
#define MODEL_Bush2             0x43
#define MODEL_Bush1             0x42
#define MODEL_Pond              0x41
#define MODEL_PondBottom        0x40
#define MODEL_PondWalls         0x3F
#define MODEL_PondSurface       0x3E
#define MODEL_Campfire          0x3D
#define MODEL_Fire              0x3C
#define MODEL_Wood2             0x3B
#define MODEL_Wood1             0x3A
#define MODEL_BigTree2          0x39
#define MODEL_TreeBigLeaves2    0x38
#define MODEL_TreeBigTrunk2     0x37
#define MODEL_BigTree1          0x36
#define MODEL_CoconutBig1       0x35
#define MODEL_TreeBigLeaves1    0x34
#define MODEL_TreeBigTrunk1     0x33
#define MODEL_Tree10            0x32
#define MODEL_Coconuts10        0x31
#define MODEL_TreeLeaves10      0x30
#define MODEL_TreeTrunk10       0x2F
#define MODEL_Tree9             0x2E
#define MODEL_Coconuts9         0x2D
#define MODEL_TreeLeaves9       0x2C
#define MODEL_TreeTrunk9        0x2B
#define MODEL_Tree8             0x2A
#define MODEL_Coconuts8         0x29
#define MODEL_TreeLeaves8       0x28
#define MODEL_TreeTrunk8        0x27
#define MODEL_Tree7             0x26
#define MODEL_Coconuts7         0x25
#define MODEL_TreeLeaves7       0x24
#define MODEL_TreeTrunk7        0x23
#define MODEL_Tree6             0x22
#define MODEL_Coconuts6         0x21
#define MODEL_TreeLeaves6       0x20
#define MODEL_TreeTrunk6        0x1F
#define MODEL_Tree5             0x1E
#define MODEL_Coconuts5         0x1D
#define MODEL_TreeLeaves5       0x1C
#define MODEL_TreeTrunk5        0x1B
#define MODEL_Tree4             0x1A
#define MODEL_Coconuts4         0x19
#define MODEL_TreeLeaves4       0x18
#define MODEL_TreeTrunk4        0x17
#define MODEL_Tree3             0x16
#define MODEL_Coconuts3         0x15
#define MODEL_TreeLeaves3       0x14
#define MODEL_TreeTrunk3        0x13
#define MODEL_Tree2             0x12
#define MODEL_Coconuts2         0x11
#define MODEL_TreeLeaves2       0x10
#define MODEL_TreeTrunk2        0xF
#define MODEL_Tree1             0xE
#define MODEL_Coconuts1         0xD
#define MODEL_TreeLeaves1       0xC
#define MODEL_TreeTrunk1        0xB
#define MODEL_Sea               0xA
#define MODEL_OceanFloor        0x9
#define MODEL_WaterSurface      0x8
#define MODEL_Waves             0x7
#define MODEL_Island            0x6
#define MODEL_Dock              0x5
#define MODEL_Trim              0x4
#define MODEL_Floor             0x3
#define MODEL_HillWall          0x2
#define MODEL_IslandWall2       0x1
#define MODEL_IslandWall1       0x0

