#define MODEL_Root              0x15
#define MODEL_Extras            0x14
#define MODEL_Rock              0x13
#define MODEL_Leaves            0x12
#define MODEL_Flowers           0x11
#define MODEL_Campfire          0x10
#define MODEL_Fire              0xF
#define MODEL_Wood2             0xE
#define MODEL_Wood1             0xD
#define MODEL_PalmTree          0xC
#define MODEL_Coconuts          0xB
#define MODEL_TreeLeaves        0xA
#define MODEL_TreeTrunk         0x9
#define MODEL_Sea               0x8
#define MODEL_OceanFloor        0x7
#define MODEL_WaterSurface      0x6
#define MODEL_Waves             0x5
#define MODEL_Island            0x4
#define MODEL_Dock              0x3
#define MODEL_FloorOuter        0x2
#define MODEL_FloorInner        0x1
#define MODEL_IslandWall        0x0

