#define COLLIDER_Root           0x1E
#define COLLIDER_LeafFlower3    0x1D
#define COLLIDER_LeafFlower2    0x1C
#define COLLIDER_LeafFlower1    0x1B
#define COLLIDER_Fence          0x1A
#define COLLIDER_Campfire       0x19
#define COLLIDER_Rock           0x18
#define COLLIDER_Bush11         0x17
#define COLLIDER_Bush10         0x16
#define COLLIDER_Bush9          0x15
#define COLLIDER_Bush8          0x14
#define COLLIDER_Bush7          0x13
#define COLLIDER_Bush6          0x12
#define COLLIDER_Bush5          0x11
#define COLLIDER_Bush4          0x10
#define COLLIDER_Bush3          0xF
#define COLLIDER_Bush2          0xE
#define COLLIDER_Bush1          0xD
#define COLLIDER_Tree10         0xC
#define COLLIDER_Tree9          0xB
#define COLLIDER_Tree8          0xA
#define COLLIDER_Tree7          0x9
#define COLLIDER_Tree6          0x8
#define COLLIDER_Tree5          0x7
#define COLLIDER_Tree4          0x6
#define COLLIDER_Tree3          0x5
#define COLLIDER_Tree2          0x4
#define COLLIDER_Tree1          0x3
#define COLLIDER_Dock           0x2
#define COLLIDER_WallsIsland    0x1
#define COLLIDER_FloorIsland    0x0

#define ZONE_Root               0x2
#define ZONE_FloorIsland        0x1
#define ZONE_Dock               0x0

