#include "trp_01.h"
#include "foliage.hpp"

namespace trp_01 {

DEFINE_PALM_TREE(PalmTree1, MODEL_TreeLeaves1, MODEL_Coconuts1, MODEL_TreeTrunk1, GEN_TREE1_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree2, MODEL_TreeLeaves2, MODEL_Coconuts2, MODEL_TreeTrunk2, GEN_TREE2_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree3, MODEL_TreeLeaves3, MODEL_Coconuts3, MODEL_TreeTrunk3, GEN_TREE3_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree4, MODEL_TreeLeaves4, MODEL_Coconuts4, MODEL_TreeTrunk4, GEN_TREE4_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree5, MODEL_TreeLeaves5, MODEL_Coconuts5, MODEL_TreeTrunk5, GEN_TREE5_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree6, MODEL_TreeLeaves6, MODEL_Coconuts6, MODEL_TreeTrunk6, GEN_TREE6_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree7, MODEL_TreeLeaves7, MODEL_Coconuts7, MODEL_TreeTrunk7, GEN_TREE7_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree8, MODEL_TreeLeaves8, MODEL_Coconuts8, MODEL_TreeTrunk8, GEN_TREE8_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree9, MODEL_TreeLeaves9, MODEL_Coconuts9, MODEL_TreeTrunk9, GEN_TREE9_VEC, 0.0f)
DEFINE_PALM_TREE(PalmTree10, MODEL_TreeLeaves10, MODEL_Coconuts10, MODEL_TreeTrunk10, GEN_TREE10_VEC, 0.0f)

DEFINE_BUSH(Bush1, MODEL_Bush1, GEN_BUSH1_VEC)
DEFINE_BUSH(Bush2, MODEL_Bush2, GEN_BUSH2_VEC)
DEFINE_BUSH(Bush3, MODEL_Bush3, GEN_BUSH3_VEC)
DEFINE_BUSH(Bush4, MODEL_Bush4, GEN_BUSH4_VEC)
DEFINE_BUSH(Bush5, MODEL_Bush5, GEN_BUSH5_VEC)
DEFINE_BUSH(Bush6, MODEL_Bush6, GEN_BUSH6_VEC)
DEFINE_BUSH(Bush7, MODEL_Bush7, GEN_BUSH7_VEC)
DEFINE_BUSH(Bush8, MODEL_Bush8, GEN_BUSH8_VEC)
DEFINE_BUSH(Bush9, MODEL_Bush9, GEN_BUSH9_VEC)
DEFINE_BUSH(Bush10, MODEL_Bush10, GEN_BUSH10_VEC)

EvtScript EVS_SetFoliage = {
    BIND_TREE(PalmTree1, COLLIDER_Tree1)
    BIND_TREE(PalmTree2, COLLIDER_Tree2)
    BIND_TREE(PalmTree3, COLLIDER_Tree3)
    BIND_TREE(PalmTree4, COLLIDER_Tree4)
    BIND_TREE(PalmTree5, COLLIDER_Tree5)
    BIND_TREE(PalmTree6, COLLIDER_Tree6)
    BIND_TREE(PalmTree7, COLLIDER_Tree7)
    BIND_TREE(PalmTree8, COLLIDER_Tree8)
    BIND_TREE(PalmTree9, COLLIDER_Tree9)
    BIND_TREE(PalmTree10, COLLIDER_Tree10)
    BIND_BUSH(Bush1, COLLIDER_Bush1)
    BIND_BUSH(Bush2, COLLIDER_Bush2)
    BIND_BUSH(Bush3, COLLIDER_Bush3)
    BIND_BUSH(Bush4, COLLIDER_Bush4)
    BIND_BUSH(Bush5, COLLIDER_Bush5)
    BIND_BUSH(Bush6, COLLIDER_Bush6)
    BIND_BUSH(Bush7, COLLIDER_Bush7)
    BIND_BUSH(Bush8, COLLIDER_Bush8)
    BIND_BUSH(Bush9, COLLIDER_Bush9)
    BIND_BUSH(Bush10, COLLIDER_Bush10)
    Return
    End
};

}; // namespace trp_01
