#!/usr/bin/env bash

set -e

nix develop --profile .nix-profile -c 'n2'

trap 'kill_all' SIGINT
trap 'kill_all' SIGTERM
kill_all() {
    echo "Bye"
    kill $BRIDGE_1 $BRIDGE_2 $GAME_1 $GAME_2
    exit 0
}

cd bridge
GDB_PORT=9123 nix develop .#bridge -c cargo watch -x "run" &
BRIDGE_1=$!
GDB_PORT=9124 nix develop .#bridge -c cargo watch -x "run" &
BRIDGE_2=$!
cd ..

ares --setting DebugServer/Port=9123 ver/us/build/papermario.z64 &
GAME_1=$!
ares --setting DebugServer/Port=9124 ver/us/build/papermario.z64 &
GAME_2=$!

wait $GAME_1
wait $GAME_2
kill_all
