#!/usr/bin/env bash

set -e

trap 'kill_all' SIGINT
trap 'kill_all' SIGTERM
kill_all() {
    echo "Bye"
    kill $CLIENT $GAME
    exit 0
}

export GDB_PORT="${GDB_PORT:-9123}"

client &
CLIENT=$!

ares --setting DebugServer/Port=$GDB_PORT ver/us/build/papermario.z64 &
GAME=$!

wait $GAME
kill_all
