#message:29:(EnemyName_Goomba) {
	Goomba[End]
}

#message:29:(EnemyName_SpikedGoomba) {
	Spiked Goomba[End]
}

#message:29:(EnemyName_Paragoomba) {
	Paragoomba[End]
}

#message:29:(EnemyName_RedGoombaBoss) {
	Red Goomba[End]
}

#message:29:(EnemyName_BlueGoombaBoss) {
	Blue Goomba[End]
}

#message:29:(EnemyName_GoombaKing) {
	Goomba King[End]
}

#message:29:(EnemyName_GoomnutTree) {
	Goomnut Tree[End]
}

#message:29:(EnemyName_KoopaTroopa) {
	Koopa Troopa[End]
}

#message:29:(EnemyName_Paratroopa) {
	Paratroopa[End]
}

#message:29:(EnemyName_Fuzzy) {
	Fuzzy[End]
}

#message:29:(EnemyName_BobOmb) {
	Bob-omb[End]
}

#message:29:(EnemyName_BulletBill) {
	Bullet Bill[End]
}

#message:29:(EnemyName_BillBlaster) {
	Bill Blaster[End]
}

#message:29:(EnemyName_FakeBowser) {
	Bowser???[End]
}

#message:29:(EnemyName_RedNinjakoopa) {
	R Ninjakoopa[End]
}

#message:29:(EnemyName_BlackNinjakoopa) {
	B Ninjakoopa[End]
}

#message:29:(EnemyName_YellowNinjakoopa) {
	Y Ninjakoopa[End]
}

#message:29:(EnemyName_GreenNinjakoopa) {
	G Ninjakoopa[End]
}

#message:29:(EnemyName_KoopaBros) {
	Koopa Bros.[End]
}

#message:29:(EnemyName_JrTroopa) {
	Jr. Troopa[End]
}

#message:29:(EnemyName_MontyMole) {
	Monty Mole[End]
}

#message:29:(EnemyName_Cleft) {
	Cleft[End]
}

#message:29:(EnemyName_Pokey) {
	Pokey[End]
}

#message:29:(EnemyName_Bandit) {
	Bandit[End]
}

#message:29:(EnemyName_PokeyMummy) {
	Pokey Mummy[End]
}

#message:29:(EnemyName_BuzzyBeetle) {
	Buzzy Beetle[End]
}

#message:29:(EnemyName_Swooper) {
	Swooper[End]
}

#message:29:(EnemyName_Buzzar) {
	Buzzar[End]
}

#message:29:(EnemyName_Tutankoopa) {
	Tutankoopa[End]
}

#message:29:(EnemyName_Chomp) {
	Chomp[End]
}

#message:29:(EnemyName_StoneChomp) {
	Stone Chomp[End]
}

#message:29:(EnemyName_PiranhaPlant) {
	Piranha Plant[End]
}

#message:29:(EnemyName_ForestFuzzy) {
	Forest Fuzzy[End]
}

#message:29:(EnemyName_HyperGoomba) {
	Hyper Goomba[End]
}

#message:29:(EnemyName_HyperParagoomba) {
	Hyper Paragoomba[End]
}

#message:29:(EnemyName_HyperCleft) {
	Hyper Cleft[End]
}

#message:29:(EnemyName_Clubba) {
	Clubba[End]
}

#message:29:(EnemyName_TubbaBlubba) {
	Tubba Blubba[End]
}

#message:29:(EnemyName_TubbaHeart) {
	Tubba's Heart[End]
}

#message:29:(EnemyName_ShyGuy) {
	Shy Guy[End]
}

#message:29:(EnemyName_GrooveGuy) {
	Groove Guy[End]
}

#message:29:(EnemyName_SpyGuy) {
	Spy Guy[End]
}

#message:29:(EnemyName_PyroGuy) {
	Pyro Guy[End]
}

#message:29:(EnemyName_SkyGuy) {
	Sky Guy[End]
}

#message:29:(EnemyName_MediGuy) {
	Medi Guy[End]
}

#message:29:(EnemyName_AntiGuy) {
	Anti Guy[End]
}

#message:29:(EnemyName_BigLanternGhost) {
	Big Lantern Ghost[End]
}

#message:29:(EnemyName_GeneralGuy) {
	General Guy[End]
}

#message:29:(EnemyName_ShySquad) {
	Shy Squad[End]
}

#message:29:(EnemyName_ShyStack) {
	Shy Stack[End]
}

#message:29:(EnemyName_StiltGuy) {
	Stilt Guy[End]
}

#message:29:(EnemyName_HurtPlant) {
	Hurt Plant[End]
}

#message:29:(EnemyName_MBush) {
	M. Bush[End]
}

#message:29:(EnemyName_JungleFuzzy) {
	Jungle Fuzzy[End]
}

#message:29:(EnemyName_SpearGuy) {
	Spear Guy[End]
}

#message:29:(EnemyName_PutridPiranha) {
	Putrid Piranha[End]
}

#message:29:(EnemyName_LavaBubble) {
	Lava Bubble[End]
}

#message:29:(EnemyName_SpikeTop) {
	Spike Top[End]
}

#message:29:(EnemyName_LavaPiranha) {
	Lava Piranha[End]
}

#message:29:(EnemyName_LavaBud) {
	Lava Bud[End]
}

#message:29:(EnemyName_PetitPiranha) {
	Petit Piranha[End]
}

#message:29:(EnemyName_Lakitu) {
	Lakitu[End]
}

#message:29:(EnemyName_Spiny) {
	Spiny[End]
}

#message:29:(EnemyName_Bzzap) {
	Bzzap![End]
}

#message:29:(EnemyName_CrazeeDayzee) {
	Crazee Dayzee[End]
}

#message:29:(EnemyName_AmazyDayzee) {
	Amazy Dayzee[End]
}

#message:29:(EnemyName_MontyMoleBoss) {
	Monty Mole[End]
}

#message:29:(EnemyName_Spike) {
	Spike?[End]
}

#message:29:(EnemyName_RuffPuff) {
	Ruff Puff[End]
}

#message:29:(EnemyName_HuffNPuff) {
	Huff N. Puff[End]
}

#message:29:(EnemyName_TuffPuff) {
	Tuff Puff[End]
}

#message:29:(EnemyName_Gulpit) {
	Gulpit[End]
}

#message:29:(EnemyName_GulpitRocks) {
	Gulpits' Rocks[End]
}

#message:29:(EnemyName_Monstar) {
	Monstar[End]
}

#message:29:(EnemyName_FrostPiranha) {
	Frost Piranha[End]
}

#message:29:(EnemyName_WhiteClubba) {
	White Clubba[End]
}

#message:29:(EnemyName_Duplighost) {
	Duplighost[End]
}

#message:29:(EnemyName_GhostWatt) {
	Watt???[End]
}

#message:29:(EnemyName_GhostKooper) {
	Kooper???[End]
}

#message:29:(EnemyName_GhostGoombario) {
	Goombario???[End]
}

#message:29:(EnemyName_GhostSushie) {
	Sushie???[End]
}

#message:29:(EnemyName_GhostLakilester) {
	Lakilester???[End]
}

#message:29:(EnemyName_GhostParakarry) {
	Parakarry???[End]
}

#message:29:(EnemyName_GhostBombette) {
	Bombette???[End]
}

#message:29:(EnemyName_GhostBow) {
	Bow???[End]
}

#message:29:(EnemyName_AlbinoDino) {
	Albino Dino[End]
}

#message:29:(EnemyName_Swoopula) {
	Swoopula[End]
}

#message:29:(EnemyName_CrystalKing) {
	Crystal King[End]
}

#message:29:(EnemyName_CrystalBit) {
	Crystal Bit[End]
}

#message:29:(EnemyName_Ember) {
	Ember[End]
}

#message:29:(EnemyName_DryBones) {
	Dry Bones[End]
}

#message:29:(EnemyName_BonyBeetle) {
	Bony Beetle[End]
}

#message:29:(EnemyName_Magikoopa) {
	Magikoopa[End]
}

#message:29:(EnemyName_Koopatrol) {
	Koopatrol[End]
}

#message:29:(EnemyName_HammerBros) {
	Hammer Bros.[End]
}

#message:29:(EnemyName_BombshellBill) {
	Bombshell Bill[End]
}

#message:29:(EnemyName_BombshellBlaster) {
	B. Bill Blaster[End]
}

#message:29:(EnemyName_Bowser) {
	Bowser[End]
}

#message:29:(EnemyName_KammyKoopa) {
	Kammy Koopa[End]
}

#message:29:(EnemyName_KentCKoopa) {
	Kent C. Koopa[End]
}

#message:29:(EnemyName_Blooper) {
	Blooper[End]
}

#message:29:(EnemyName_ElectroBlooper) {
	Electro Blooper[End]
}

#message:29:(EnemyName_SuperBlooper) {
	Super Blooper[End]
}

#message:29:(EnemyName_BlooperBaby) {
	Blooper Baby[End]
}

#message:29:(EnemyName_TheMaster) {
	The Master[End]
}

#message:29:(EnemyName_Chan) {
	Chan[End]
}

#message:29:(EnemyName_Lee) {
	Lee[End]
}

#message:29:(EnemyName_Gloomba) {
	Gloomba[End]
}

#message:29:(EnemyName_Paragloomba) {
	Paragloomba[End]
}

#message:29:(EnemyName_SpikedGloomba) {
	Spiked Gloomba[End]
}

#message:29:(EnemyName_DarkKoopa) {
	Dark Koopa[End]
}

#message:29:(EnemyName_DarkParatroopa) {
	D. Paratroopa[End]
}

#message:29:(EnemyName_RedMagikoopa) {
	R Magikoopa[End]
}

#message:29:(EnemyName_GreenMagikoopa) {
	GRN Magikoopa[End]
}

#message:29:(EnemyName_YellowMagikoopa) {
	Y Magikoopa[End]
}

#message:29:(EnemyName_GrayMagikoopa) {
	GRY Magikoopa[End]
}

#message:29:(EnemyName_WhiteMagikoopa) {
	W Magikoopa[End]
}

#message:29:(EnemyName_Mario) {
	Mario[End]
}

#message:29:(EnemyName_SlotMachineStart) {
	Slot Machine (start)[End]
}

#message:29:(EnemyName_SlotMachineStop) {
	Slot Machine (stop)[End]
}

#message:29:(EnemyName_Whacka) {
	Whacka[End]
}

#message:29:(EnemyName_GeneralGuyDup) {
	General Guy[End]
}

#message:29:(EnemyName_Bulb) {
	Bulb[End]
}

#message:29:(EnemyName_ShySquadRedux) {
	Shy Squad[End]
}

#message:29:(EnemyName_Fuzzipede) {
	Fuzzipede[End]
}

#message:29:(EnemyName_MontyHole) {
	Monty's Hole[End]
}

#message:29:(EnemyName_Balloon) {
	Balloon[End]
}

#message:29:(EnemyName_Lantern) {
	Lantern[End]
}

#message:29:(EnemyName_AquaFuzzy) {
	Aqua Fuzzy[End]
}

#message:29:(EnemyName_RedGoomba) {
	Red Goomba[End]
}

#message:29:(EnemyName_RedParagoomba) {
	R Paragoomba[End]
}

#message:29:(EnemyName_MechaBlooper) {
	Mecha Blooper[End]
}
