#message:2F:(Online_SearchingForGateway) {
	[Style narrate]
	Searching for gateway...[BR]
	[Yield][End]
}

#message:2F:(Online_ConnectingToServer) {
	[Next]
	Connecting to server...[BR]
	[Yield][End]
}

#message:2F:(Online_Connected) {
	[Next]
	Connected![BR]
	[Yield][End]
}

#message:2F:(MoveName_RallyWink) {
	Rally Wink[End]
}

#message:2F:(MoveDesc_RallyWink) {
	Give your shipmate an extra[BR]
	turn to attack.[End]
}
